title: The Urdu Post | TMP News
description: "The Urdu Post (TMP News) - Latest Urdu News, Global Politics, Analysis and Breaking News from TMP News Agency."
permalink: /news/:categories/:title/

# Site-wide SEO keywords
keywords: ["The Urdu Post", "TMP News", "Urdu News", "World Politics", "Indian Politics", "Global Affairs", "Technology", "Global Economy"]

# Add this section to explicitly enable the sitemap plugin
plugins:
  - jekyll-sitemap
  - jekyll-feed

baseurl: "" 
url: "https://theurdupost.tmpnews.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Tell Jekyll to process the _live_updates and _authors folders as collections
collections:
  live_updates:
    output: true 
  authors:
    output: true
    permalink: /author/:name/

# Tell Jekyll to include these files/folders in the final build
include:
  - cms.html
  - liveCMS.html
  - latest.html
  - about.html
  - news-hub.html 
  - post.html
  - .well-known
  - auth-callback.html
  - write.html
  - founder.html
# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - _article_repos/